services:
  database:
    image: mariadb:11
    ports:
      - "3309:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: "express"

  express:
    image: node:23
    env_file:
      - ./.env
    ports:
      - "8090:3000"
    volumes:
      - ./backend/app:/app
      - ./backend/app/uploads:/app/uploads
    command: 'sh -c "cd /app && npm install && npm install mysql && npm run start"'

  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "3001:80"
